// Mocks generated by Mockito 5.4.6 from annotations
// in dri_survey/test/data_export_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dri_survey/services/database_service.dart' as _i3;
import 'package:dri_survey/services/excel_service.dart' as _i5;
import 'package:excel/excel.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  set currentSessionId(String? id) => super.noSuchMethod(
        Invocation.setter(
          #currentSessionId,
          id,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveVillageDrainageWaste(
    String? sessionId,
    Map<String, dynamic>? drainageData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveVillageDrainageWaste,
          [
            sessionId,
            drainageData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSurveySession(String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSurveySession,
          [phoneNumber],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> createNewSurveyRecord(Map<String, dynamic>? surveyData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewSurveyRecord,
          [surveyData],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllVillageSurveySessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllVillageSurveySessions,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllSurveySessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSurveySessions,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getSurveySession(String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSurveySession,
          [phoneNumber],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> updateSurveyStatus(
    String? phoneNumber,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSurveyStatus,
          [
            phoneNumber,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSurveySyncStatus(
    String? phoneNumber,
    String? syncStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSurveySyncStatus,
          [
            phoneNumber,
            syncStatus,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markFamilyPageCompleted(
    String? phoneNumber,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markFamilyPageCompleted,
          [
            phoneNumber,
            page,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markFamilyPageSynced(
    String? phoneNumber,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markFamilyPageSynced,
          [
            phoneNumber,
            page,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markVillagePageCompleted(
    String? sessionId,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markVillagePageCompleted,
          [
            sessionId,
            page,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markVillagePageSynced(
    String? sessionId,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markVillagePageSynced,
          [
            sessionId,
            page,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getFamilyPageStatus(String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFamilyPageStatus,
          [phoneNumber],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getVillagePageStatus(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVillagePageStatus,
          [sessionId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getIncompleteFamilySurveys() =>
      (super.noSuchMethod(
        Invocation.method(
          #getIncompleteFamilySurveys,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getIncompleteVillageSurveys() =>
      (super.noSuchMethod(
        Invocation.method(
          #getIncompleteVillageSurveys,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> updateVillageSurveySyncStatus(
    String? sessionId,
    String? syncStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVillageSurveySyncStatus,
          [
            sessionId,
            syncStatus,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateVillageSurveySession(
    String? sessionId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVillageSurveySession,
          [
            sessionId,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveData(
    String? tableName,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveData,
          [
            tableName,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteByPhone(
    String? tableName,
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteByPhone,
          [
            tableName,
            phoneNumber,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getData(
    String? tableName,
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [
            tableName,
            phoneNumber,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUnsyncedFamilySurveys() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedFamilySurveys,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUnsyncedVillageSurveys() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedVillageSurveys,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> createNewVillageSurveySession(
          Map<String, dynamic>? sessionData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewVillageSurveySession,
          [sessionData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getVillageSurveySession(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVillageSurveySession,
          [sessionId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getVillageData(
    String? tableName,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVillageData,
          [
            tableName,
            sessionId,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getVillageSurveyByShineCode(
          String? shineCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVillageSurveyByShineCode,
          [shineCode],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getVillageScreenData(
    String? identifier,
    String? tableName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVillageScreenData,
          [
            identifier,
            tableName,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> createVillageSurveySession(
          Map<String, dynamic>? sessionData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVillageSurveySession,
          [sessionData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateVillageSurveyStatus(
    String? sessionId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVillageSurveyStatus,
          [
            sessionId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertOrUpdate(
    String? tableName,
    Map<String, dynamic>? data,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertOrUpdate,
          [
            tableName,
            data,
            sessionId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ExcelService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExcelService extends _i1.Mock implements _i5.ExcelService {
  MockExcelService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> exportCompleteSurveyToExcel(String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportCompleteSurveyToExcel,
          [phoneNumber],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> exportAllSurveysToExcel() => (super.noSuchMethod(
        Invocation.method(
          #exportAllSurveysToExcel,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> exportCompleteSurveyData(String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportCompleteSurveyData,
          [phoneNumber],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> exportCompleteVillageSurveyToExcel(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportCompleteVillageSurveyToExcel,
          [sessionId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> fetchCompleteSurveyData(
          String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCompleteSurveyData,
          [phoneNumber],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> fetchCompleteVillageSurveyData(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCompleteVillageSurveyData,
          [sessionId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> createComprehensiveReport(
    _i6.Sheet? sheet,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComprehensiveReport,
          [
            sheet,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createVillageSurveyReport(
    _i6.Sheet? sheet,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVillageSurveyReport,
          [
            sheet,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> exportSurveyToExcel(Map<String, dynamic>? surveyData) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportSurveyToExcel,
          [surveyData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
