// Generated from database_supabase_sqlite/schema at supbase.sql
// Map of remote table -> primary key column list in order

const Map<String, List<String>> kHardcodedRemotePrimaryKeys = {
  // All keys confirmed against schema at supbase.sql
  'aadhaar_info': ['phone_number'],
  'aadhaar_scheme_members': ['phone_number', 'sr_no'],
  'agricultural_equipment': ['phone_number'],
  'animals': ['phone_number', 'sr_no'],
  'ayushman_card': ['phone_number'],
  'ayushman_scheme_members': ['phone_number', 'sr_no'],
  'bank_accounts': ['phone_number', 'sr_no'],
  'child_diseases': ['phone_number', 'sr_no'],
  'children_data': ['phone_number'],
  'crop_productivity': ['phone_number', 'sr_no'],
  'diseases': ['phone_number', 'sr_no'],
  'disputes': ['phone_number'],
  'drinking_water_sources': ['phone_number'],
  'entertainment_facilities': ['phone_number'],
  'family_id': ['phone_number'],
  'family_id_scheme_members': ['phone_number', 'sr_no'],
  'family_members': ['phone_number', 'sr_no'],
  'family_survey_sessions': ['phone_number'],
  'fertilizer_usage': ['phone_number'],
  'folklore_medicine': ['phone_number'],
  'fpo_members': ['phone_number', 'sr_no'],
  'handicapped_allowance': ['phone_number'],
  'handicapped_scheme_members': ['phone_number', 'sr_no'],
  'health_programmes': ['phone_number'],
  'house_conditions': ['phone_number'],
  'house_facilities': ['phone_number'],
  'irrigation_facilities': ['phone_number'],
  'kisan_credit_card': ['phone_number'],
  'kisan_credit_card_members': ['phone_number', 'sr_no'],
  'land_holding': ['phone_number'],
  'malnourished_children_data': ['phone_number', 'sr_no'],
  'medical_treatment': ['phone_number'],

  'migration_data': ['phone_number', 'sr_no'],
  'nutritional_garden': ['phone_number'],
  'pension_allowance': ['phone_number'],
  'pension_scheme_members': ['phone_number', 'sr_no'],
  'pm_kisan_members': ['phone_number', 'sr_no'],
  'pm_kisan_nidhi': ['phone_number'],
  'pm_kisan_samman_members': ['phone_number', 'sr_no'],
  'pm_kisan_samman_nidhi': ['phone_number'],
  'ration_card': ['phone_number'],
  'ration_scheme_members': ['phone_number', 'sr_no'],
  'samagra_id': ['phone_number'],
  'samagra_scheme_members': ['phone_number', 'sr_no'],
  'shg_members': ['phone_number', 'sr_no'],
  'social_consciousness': ['phone_number'],
  'spatial_ref_sys': ['srid'],
  'swachh_bharat_mission': ['phone_number'],
  'swachh_bharat_mission_members': ['phone_number', 'sr_no'],
  'training_data': ['phone_number', 'sr_no'],
  'training_needs': ['phone_number', 'sr_no'],
  'transport_facilities': ['phone_number'],
  'tribal_card': ['phone_number'],
  'tribal_questions': ['phone_number'],
  'tribal_scheme_members': ['phone_number', 'sr_no'],
  'tulsi_plants': ['phone_number'],
  'fasal_bima': ['phone_number'],
  'fasal_bima_members': ['phone_number', 'sr_no'],
  'vb_gram': ['phone_number'],
  'vb_gram_members': ['phone_number', 'sr_no'],
  'village_agricultural_implements': ['session_id'],
  'village_animals': ['session_id', 'sr_no'],
  'village_biodiversity_register': ['session_id'],
  'village_bpl_families': ['session_id'],
  'village_cadastral_maps': ['session_id'],
  'village_children_data': ['session_id'],
  'village_crop_productivity': ['session_id', 'sr_no'],
  'village_disputes': ['session_id'],
  'village_drainage_waste': ['session_id'],
  'village_drinking_water': ['session_id'],
  'village_educational_facilities': ['session_id'],
  'village_entertainment': ['session_id'],
  'village_farm_families': ['session_id'],
  'village_forest_maps': ['session_id'],
  'village_housing': ['session_id'],
  'village_infrastructure': ['session_id'],
  'village_infrastructure_details': ['session_id'],
  'village_irrigation_facilities': ['session_id'],
  'village_kitchen_gardens': ['session_id'],
  'village_malnutrition_data': ['session_id', 'sr_no'],
  'village_map_points': ['session_id', 'point_id'],
  'village_medical_treatment': ['session_id'],
  'village_population': ['session_id'],
  'village_seed_clubs': ['session_id'],
  'village_signboards': ['session_id', 'sr_no'],
  'village_social_consciousness': ['session_id'],
  'village_social_maps': ['session_id', 'sr_no'],
  'village_survey_details': ['session_id'],
  'village_survey_sessions': ['session_id'],
  'village_traditional_occupations': ['session_id', 'sr_no'],
  'village_transport': ['session_id'],
  'village_transport_facilities': ['session_id'],
  'village_unemployment': ['session_id'],
  'widow_allowance': ['phone_number'],
  'widow_scheme_members': ['phone_number', 'sr_no'],
};
